### ISSUE TITLE
Frage nach Immunsystem

### ISSUE THREAD

**Issue by JohannesLamberts** [JohannesLamberts/coronav#13]
Es soll eine weitere Frage eingefügt werden, die nur angezeigt wird, wenn die Fragen nach Vorerkrankung und Alter verneint wurden:

Haben Sie ein unterdrücktes Immunsystem?

zum Beispiel wegen:
- Organtransplantation
- Krebserkrankung
- Chemotherapie
- Cortison Tabletten-Einnahme - HIV

Ein JA wirkt sich aus wie andere Risikofaktoren. Entsprechend müssen die Ergebnistexte angepasst werden.

**Comment by StefanieStoppel** [comment]
Wurde mit Merge Request #20 hinzugefügt.
