### ISSUE TITLE
Anpassung "Risikogebiete" an neue Empfehlung des RKI

### ISSUE THREAD

**Issue by JohannesLamberts** [JohannesLamberts/coronav#14]
Das RKI hat seine Empfehlung zu einem Verdacht auf COVID-19 angepasst. Jetzt:

- Personen mit akuten respiratorischen Symptomen jeder Schwere UND Kontakt mit einem bestätigten Fall von COVID-19
- Auftreten von zwei oder mehr Lungenentzündungen (Pneumonien) in einer medizinischen Einrichtung, einem Pflege- oder Altenheim, bei denen ein epidemischer Zusammenhang wahrscheinlich ist oder vermutet wird, auch ohne Vorliegen eines Erregernachweises.

Entsprechend müssen die Fragen angepasst werden (TBD).

**Comment by StefanieStoppel** [comment]
Fragebogen wurde aktualisiert mit Merge Request #20.
